version: '3.4'

services:
  app:
    build: ./docker/app
    restart: always
    ports:
      - '${IP}:${PORT}:${PORT}' # app
      - '${IP}:6006:6006' # storybook
    volumes:
      - ./:/app
      - next:/app/.next/
    command: sh -c "yarn && yarn run dev"
    environment:
      CHOKIDAR_USEPOLLING: 'true'
      NODE_ENV: development
      PORT: ${PORT}
      MICROCMS_SERVICE_DOMAIN: ${MICROCMS_SERVICE_DOMAIN}
      MICROCMS_API_KEY: ${MICROCMS_API_KEY}
      BASE_URL: ${BASE_URL}

volumes:
  next:
    driver: local
