name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master  
      - name: setting config
        run: cp ./src/app/firebase/config.ts.example config.ts \
          & sed -i s/FIREBASE_APIKEY/${{ secrets.FIREBASE_APIKEY }}/ config.ts \
          & sed -i s/FIREBASE_APPID/${{ secrets.FIREBASE_APPID }}/ config.ts \
          & sed -i s/FIREBASE_AUTHDOMAIN/${{ secrets.FIREBASE_AUTHDOMAIN }}/ config.ts \
          & sed -i s/FIREBASE_DATABASEURL/${{ secrets.FIREBASE_DATABASEURL }}/ config.ts \
          & sed -i s/FIREBASE_MEASUREMENT_ID/${{ secrets.FIREBASE_MEASUREMENT_ID }}/ config.ts \
          & sed -i s/FIREBASE_MESSAGING_SENDER_ID/${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}/ config.ts \
          & sed -i s/FIREBASE_PROJECTID/${{ secrets.FIREBASE_PROJECTID }}/ config.ts \
          & sed -i s/FIREBASE_STORAGEBUCKET/${{ secrets.FIREBASE_STORAGEBUCKET }}/ config.ts /
          & mv config.ts ./src/app/firebase/config.ts
      - name: npm install
        run: npm install
      - name: GitHub Action for Firebase
        uses: w9jds/firebase-action@v1.1.0
        with:
          args: deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
