name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master  
      - name: npm install
        run: npm install
      - name: GitHub Action for Firebase
        uses: w9jds/firebase-action@v1.1.0
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
