name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master  
      - name: npm install
        run: npm rebuild & npm install
      - name: set config
        run: |
          touch ./src/app/.env
          echo FIREBASE_APIKEY=${{ secrets.FIREBASE_APIKEY }} >> ./src/app/.env
          echo FIREBASE_APPID=${{ secrets.FIREBASE_APPID }} >> ./src/app/.env
          echo FIREBASE_AUTHDOMAIN=${{ secrets.FIREBASE_AUTHDOMAIN }} >> ./src/app/.env
          echo FIREBASE_DATABASEURL=${{ secrets.FIREBASE_DATABASEURL }} >> ./src/app/.env
          echo FIREBASE_MEASUREMENT_ID=${{ secrets.FIREBASE_MEASUREMENT_ID }} >> ./src/app/.env
          echo FIREBASE_MESSAGING_SENDER_ID=${{ secrets.FIREBASE_MESSAGING_SENDER_ID }} >> ./src/app/.env
          echo FIREBASE_PROJECTID=${{ secrets.FIREBASE_PROJECTID }} >> ./src/app/.env
          echo FIREBASE_STORAGEBUCKET=${{ secrets.FIREBASE_STORAGEBUCKET }} >> ./src/app/.env
      - name: GitHub Action for Firebase
        uses: w9jds/firebase-action@v1.1.0
        with:
          args: deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
