name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master  
      - name: npm install
        run: npm install
      - name: setting config
        run: cp ./src/app/firebase/config.ts.example ./src/app/firebase/config.ts \
          sed ./src/app/firebase/config.ts s/FIREBASE_APIKEY/${{ secrets.FIREBASE_APIKEY }}/ \
          sed ./src/app/firebase/config.ts s/FIREBASE_APPID/${{ secrets.FIREBASE_APPID }}/ \
          sed ./src/app/firebase/config.ts s/FIREBASE_AUTHDOMAIN/${{ secrets.FIREBASE_AUTHDOMAIN }}/ \
          sed ./src/app/firebase/config.ts s/FIREBASE_DATABASEURL/${{ secrets.FIREBASE_DATABASEURL }}/ \
          sed ./src/app/firebase/config.ts s/FIREBASE_MEASUREMENT_ID/${{ secrets.FIREBASE_MEASUREMENT_ID }}/ \
          sed ./src/app/firebase/config.ts s/FIREBASE_MESSAGING_SENDER_ID/${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}/ \
          sed ./src/app/firebase/config.ts s/FIREBASE_PROJECTID/${{ secrets.FIREBASE_PROJECTID }}/ \
          sed ./src/app/firebase/config.ts s/FIREBASE_STORAGEBUCKET/${{ secrets.FIREBASE_STORAGEBUCKET }}/
      - name: GitHub Action for Firebase
        uses: w9jds/firebase-action@v1.1.0
        with:
          args: deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
